# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from communication import protocol_pb2 as communication_dot_protocol__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in communication/protocol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTensor = channel.unary_unary(
                '/distributed.WorkerService/SendTensor',
                request_serializer=communication_dot_protocol__pb2.TensorMessage.SerializeToString,
                response_deserializer=communication_dot_protocol__pb2.TensorResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/distributed.WorkerService/Ping',
                request_serializer=communication_dot_protocol__pb2.PingRequest.SerializeToString,
                response_deserializer=communication_dot_protocol__pb2.PingResponse.FromString,
                _registered_method=True)
        self.TrainStep = channel.unary_unary(
                '/distributed.WorkerService/TrainStep',
                request_serializer=communication_dot_protocol__pb2.TrainStepRequest.SerializeToString,
                response_deserializer=communication_dot_protocol__pb2.TrainStepResponse.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/distributed.WorkerService/Configure',
                request_serializer=communication_dot_protocol__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=communication_dot_protocol__pb2.Ack.FromString,
                _registered_method=True)
        self.AbortStep = channel.unary_unary(
                '/distributed.WorkerService/AbortStep',
                request_serializer=communication_dot_protocol__pb2.StepControl.SerializeToString,
                response_deserializer=communication_dot_protocol__pb2.Ack.FromString,
                _registered_method=True)
        self.CommitStep = channel.unary_unary(
                '/distributed.WorkerService/CommitStep',
                request_serializer=communication_dot_protocol__pb2.StepControl.SerializeToString,
                response_deserializer=communication_dot_protocol__pb2.Ack.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/distributed.WorkerService/GetState',
                request_serializer=communication_dot_protocol__pb2.PingRequest.SerializeToString,
                response_deserializer=communication_dot_protocol__pb2.StateResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SendTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTensor,
                    request_deserializer=communication_dot_protocol__pb2.TensorMessage.FromString,
                    response_serializer=communication_dot_protocol__pb2.TensorResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=communication_dot_protocol__pb2.PingRequest.FromString,
                    response_serializer=communication_dot_protocol__pb2.PingResponse.SerializeToString,
            ),
            'TrainStep': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainStep,
                    request_deserializer=communication_dot_protocol__pb2.TrainStepRequest.FromString,
                    response_serializer=communication_dot_protocol__pb2.TrainStepResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=communication_dot_protocol__pb2.ConfigureRequest.FromString,
                    response_serializer=communication_dot_protocol__pb2.Ack.SerializeToString,
            ),
            'AbortStep': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortStep,
                    request_deserializer=communication_dot_protocol__pb2.StepControl.FromString,
                    response_serializer=communication_dot_protocol__pb2.Ack.SerializeToString,
            ),
            'CommitStep': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitStep,
                    request_deserializer=communication_dot_protocol__pb2.StepControl.FromString,
                    response_serializer=communication_dot_protocol__pb2.Ack.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=communication_dot_protocol__pb2.PingRequest.FromString,
                    response_serializer=communication_dot_protocol__pb2.StateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.WorkerService/SendTensor',
            communication_dot_protocol__pb2.TensorMessage.SerializeToString,
            communication_dot_protocol__pb2.TensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.WorkerService/Ping',
            communication_dot_protocol__pb2.PingRequest.SerializeToString,
            communication_dot_protocol__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.WorkerService/TrainStep',
            communication_dot_protocol__pb2.TrainStepRequest.SerializeToString,
            communication_dot_protocol__pb2.TrainStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.WorkerService/Configure',
            communication_dot_protocol__pb2.ConfigureRequest.SerializeToString,
            communication_dot_protocol__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.WorkerService/AbortStep',
            communication_dot_protocol__pb2.StepControl.SerializeToString,
            communication_dot_protocol__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.WorkerService/CommitStep',
            communication_dot_protocol__pb2.StepControl.SerializeToString,
            communication_dot_protocol__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.WorkerService/GetState',
            communication_dot_protocol__pb2.PingRequest.SerializeToString,
            communication_dot_protocol__pb2.StateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/distributed.CoordinatorService/RegisterWorker',
                request_serializer=communication_dot_protocol__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=communication_dot_protocol__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.StartTraining = channel.unary_unary(
                '/distributed.CoordinatorService/StartTraining',
                request_serializer=communication_dot_protocol__pb2.TrainingRequest.SerializeToString,
                response_deserializer=communication_dot_protocol__pb2.TrainingResponse.FromString,
                _registered_method=True)
        self.GetClusterStatus = channel.unary_unary(
                '/distributed.CoordinatorService/GetClusterStatus',
                request_serializer=communication_dot_protocol__pb2.ClusterStatusRequest.SerializeToString,
                response_deserializer=communication_dot_protocol__pb2.ClusterStatusResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=communication_dot_protocol__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=communication_dot_protocol__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'StartTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=communication_dot_protocol__pb2.TrainingRequest.FromString,
                    response_serializer=communication_dot_protocol__pb2.TrainingResponse.SerializeToString,
            ),
            'GetClusterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterStatus,
                    request_deserializer=communication_dot_protocol__pb2.ClusterStatusRequest.FromString,
                    response_serializer=communication_dot_protocol__pb2.ClusterStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.CoordinatorService/RegisterWorker',
            communication_dot_protocol__pb2.RegisterWorkerRequest.SerializeToString,
            communication_dot_protocol__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.CoordinatorService/StartTraining',
            communication_dot_protocol__pb2.TrainingRequest.SerializeToString,
            communication_dot_protocol__pb2.TrainingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed.CoordinatorService/GetClusterStatus',
            communication_dot_protocol__pb2.ClusterStatusRequest.SerializeToString,
            communication_dot_protocol__pb2.ClusterStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
